# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tS6SBcWAVJ-txiYAehkMuSZQMR2GzmUN

Q1.
"""

s = "Prudvi"
l = [1,3,5.4,'A',"Prudvi"]
f = 4.6
t = (1,3,7.9,'B',"Kumar")

print(s)
print(l)
print(f)
print(t)

"""Q2.
  1)string
  2)string
  3)list
  4)int

Q3.  1)division 2)remainder 3)floor division 4)power

Q4.
"""

list = [2,3,5,4,4,"Reddy",4.8,'A',2+8j]
for i in list:
  print(i)
  print(type(i))

"""Q5."""

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c=0
while(a%b==0):
  a=a//b
  c+=1
  if b==1:
    c="infinite"
    break
  if a<=0:
    break
print(c)

"""Q6."""

lst=list(range(25))
c=0
for i in lst:
  if i%3==0:
    c+=1
print(c)

"""Q7. mutables data types are changable but immutable 
    datatypes are not changable. For example,
"""

list = [2,3,4]
list[1]=5 #no error

str="prudvi"
str[1]="R" #error